# README

### Inserting another Database:
    1) have the last column be Y and the previous columns be X
    
    2) Add database to name df_list_name and refernce to df_list
        -- after clean up section
        
    3) Add another df object to the stats class

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
from sklearn import svm
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier

# Load Data Files from UCI ML

In [2]:
#df_winequality_red = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv')
#abalone_header = ['sex', 'len', 'diam','height','tot-weight','shuck_weigth','Visc_weight;]
#df_tele = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data', names = tele_header)

df_winequality_red = pd.read_csv('winequality-red.csv')
df_winequality_whi = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv', sep=';')

abalone_header = ['sex', 'len', 'diam','height','tot-weight','shuck_weigth','Visc_weight', 'shell_weight', 'rings']
df_abalone =pd.read_csv('abalone.data', names = abalone_header)

tele_header = ['fLen', 'fWidth', 'fsize', 'fConc', 'fConc1', 'fAsym','fM3Long','fM3Trans','fAlpha','fDist','class']
df_tele = pd.read_csv('magic04.data', names = tele_header)
df_iris = pd.read_csv('Iris.csv')

#df_adult = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data')

# Make df_Tele 10% its normal size
df_tele = df_tele.sample(frac = 0.05)
df_abalone = df_abalone.sample(frac = 0.2)
df_winequality_whi = df_winequality_whi.sample(frac = 0.2)

# Clean adult database

In [3]:
#pd.get_dummies(pd.Series(list(df_adult['Bachelors'].values)))

# Clean abalone df

In [4]:
df_abalone.insert(0, 'infant', df_abalone['sex'] == 'I')
df_abalone['infant'] = df_abalone['infant'].astype(int)

df_abalone.insert(0, 'male', df_abalone['sex'] == 'M')
df_abalone['male'] = df_abalone['male'].astype(int)

df_abalone.insert(0, 'female', df_abalone['sex'] == 'F')
df_abalone['female'] = df_abalone['female'].astype(int)

df_abalone['old'] = df_abalone['rings'] >= df_abalone['rings'].mean()
df_abalone['old'] = df_abalone['old'].astype(int)

df_abalone = df_abalone.drop(columns = ['sex'])
df_abalone = df_abalone.drop(columns = ['rings'])

In [5]:
df_abalone.head()

,female,male,infant,len,diam,height,tot-weight,shuck_weigth,Visc_weight,shell_weight,old
369,1,0,0,0.690,0.560,0.215,1.7190,0.6800,0.2990,0.4700,1
470,1,0,0,0.530,0.440,0.135,0.7835,0.3130,0.1715,0.2185,0
2791,0,1,0,0.625,0.500,0.140,1.0960,0.5445,0.2165,0.2950,1
2336,1,0,0,0.565,0.480,0.175,0.9570,0.3885,0.2150,0.2750,1
417,0,1,0,0.630,0.515,0.165,1.3520,0.4880,0.3490,0.4500,1

# Clean Wine Quality DF

In [6]:
df_winequality_whi['qaulity_y'] = df_winequality_whi['quality'] >= 6
df_winequality_whi['qaulity_y'] = df_winequality_whi['qaulity_y'].astype(int)
df_winequality_whi = df_winequality_whi.drop(columns = ['quality'])

df_winequality_red['qaulity_y'] = df_winequality_red['quality'] >= 6
df_winequality_red['qaulity_y'] = df_winequality_red['qaulity_y'].astype(int)
df_winequality_red = df_winequality_red.drop(columns = ['quality'])

In [7]:
df_winequality_red.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,qaulity_y
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,1
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0

# Clean Tele df

In [8]:
df_tele['class'] = df_tele['class'] == 'g'
df_tele['class'] = df_tele['class'].astype(int)

In [9]:
df_tele.head()

,fLen,fWidth,fsize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
3792,12.8000,11.5493,2.1383,0.7273,0.3818,-15.2423,6.6145,-11.3669,63.8866,164.209,1
14169,173.1370,45.9980,3.2298,0.2851,0.1770,-136.8590,24.3254,14.8392,48.6757,299.590,0
7290,38.7504,15.5010,2.6508,0.4067,0.2112,-29.3864,-35.3548,11.4233,13.6657,175.622,1
7852,39.5085,20.9302,2.7828,0.2935,0.1772,-19.8992,-33.7291,19.4858,4.7427,236.413,1
14504,39.6937,16.9156,2.5343,0.4122,0.2092,-44.6689,26.3372,-6.2138,54.3820,106.480,0

# Clean Iris DF

In [10]:
# set df_iris['y'] == 1 if its setosa or vericolor
df_iris['y'] = (df_iris['Species'] == 'Iris-setosa') | (df_iris['Species'] == 'Iris-versicolor')
df_iris = df_iris.drop(columns = ['Id', 'Species'])
df_iris['y'] = df_iris['y'].astype(int)

In [11]:
df_iris.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  y
0            5.1           3.5            1.4           0.2  1
1            4.9           3.0            1.4           0.2  1
2            4.7           3.2            1.3           0.2  1
3            4.6           3.1            1.5           0.2  1
4            5.0           3.6            1.4           0.2  1

# Lists for grid Search

In [12]:
C_list    = [0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1]
depth_set = [1, 2, 3, 4, 5]
k_list    = [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 15, 17, 21, 25, 29, 31, 33]

df_name_list = ['Wine Quality Red', 'Abalone', 'Telescope', 'Wine Quality White']
df_list = [df_winequality_red, df_abalone, df_tele, df_winequality_whi]

In [13]:
def test_train_split(df, perc):    
    X_and_Y = df.values
    np.random.shuffle(X_and_Y)    # Shuffle the data.
    
    X = X_and_Y[:,:X_and_Y.shape[1]-2]  # Shape: (300,)
    Y = X_and_Y[:,X_and_Y.shape[1]-1].reshape((X_and_Y.shape[0],1)) 

    train_Num = int(X.shape[0]*perc)

    X_train_val = X[: train_Num, :] # Get features from train + val set.
    X_test      = X[train_Num :, :] # Get features from test set.     
    Y_train_val = Y[: train_Num, :] # Get labels from train + val set.
    Y_test      = Y[train_Num :, :] # Get labels from test set.  

    return (X_train_val, X_test, Y_train_val, Y_test)

# Grid Search Functions

In [14]:
def svc_grid(X_train_val, Y_train_val):    
    classifier = svm.SVC(kernel= 'linear', C=C_list)
    parameters = {'C':C_list}

    grid_Search = GridSearchCV(classifier, parameters, cv=3, return_train_score='true', scoring='accuracy')
    grid_Search.fit(X_train_val, Y_train_val.reshape(-1))
    
    return grid_Search

def dec_tree_grid(X_train_val, Y_train_val):    
    classifier = tree.DecisionTreeClassifier()
    params = {'criterion': ['entropy'], 'max_depth' : depth_set}

    grid_Search = GridSearchCV(classifier, params, cv=3, return_train_score = 'true', scoring='accuracy')
    grid_Search.fit(X_train_val, Y_train_val.reshape(-1))
  
    return grid_Search

def knn_grid(X_train_val, Y_train_val):       
    classifier = KNeighborsClassifier()    
    
    param_grid = dict(n_neighbors=k_list)
   
    grid_Search = GridSearchCV(classifier, param_grid, cv=3, return_train_score = 'true', scoring='accuracy')
    grid_Search.fit(X_train_val, Y_train_val.reshape(-1))
  
    return grid_Search

# Draw heatmaps for data

In [15]:
def compile_heatmaps(grid_Search, params):
    train_acc = np.array([grid_Search.cv_results_['mean_train_score']]).reshape(len(params),1)
    draw_heatmap_linear(train_acc, 'train accuracy', params)

    val_acc = np.array([grid_Search.cv_results_['mean_test_score']]).reshape(len(params),1)
    draw_heatmap_linear(val_acc, 'val accuracy', params)

def draw_heatmap_linear(acc, acc_desc, params):
    plt.figure(figsize = (2,4))
    ax = sns.heatmap(acc, annot=True, fmt='.3f', yticklabels=params, xticklabels=[])
    ax.collections[0].colorbar.set_label("accuracy")
    ax.set(ylabel='$C$')
    plt.title(acc_desc + ' w.r.t $C$')
    sns.set_style("whitegrid", {'axes.grid' : False})
    plt.show()

# 3 Different Algorithms

In [16]:
def fit_best_est(grid_Search, X_train_val, X_test, Y_train_val, Y_test):
    
        clf = grid_Search.best_estimator_
        clf.fit(X_train_val, Y_train_val.reshape(-1))

        test_acc  = clf.score(X_test, Y_test.reshape(-1))
        train_acc = grid_Search.cv_results_['mean_train_score'][grid_Search.best_index_]
        val_acc   = grid_Search.cv_results_['mean_test_score'][grid_Search.best_index_]

        if show_heatmaps:
            compile_heatmaps(grid_Search, depth_set)
            print("Best parameters: ", grid_Search.best_params_)   
            
        return test_acc, train_acc, val_acc

In [17]:
def do_svc(df, perc):
    X_train_val, X_test, Y_train_val, Y_test = test_train_split(df, perc)
    grid_Search = svc_grid(X_train_val, Y_train_val)  
    
    return fit_best_est(grid_Search, X_train_val, X_test, Y_train_val, Y_test)

def do_dec_tree(df, perc):
    X_train_val, X_test, Y_train_val, Y_test = test_train_split(df, perc)
    grid_Search = dec_tree_grid(X_train_val, Y_train_val)     
    
    return fit_best_est(grid_Search, X_train_val, X_test, Y_train_val, Y_test)

def do_knn(df, perc):
    X_train_val, X_test, Y_train_val, Y_test = test_train_split(df, perc)
    grid_Search = knn_grid(X_train_val, Y_train_val)  
     
    return fit_best_est(grid_Search, X_train_val, X_test, Y_train_val, Y_test)

# Data Structure to Hold all of the accuracies

In [18]:
num_kernels = 3
train_list = [0.2, 0.5, 0.8]

class stats_i:
    def __init__(self):
        self.acc = {
          "train_acc": [],
          "val_acc"  : [],
          "test_acc" : []
        }
    def populate_stats(self, test_acc, train_acc, val_acc):
        self.acc['train_acc'].append(int(train_acc*1000)/1000)
        self.acc['test_acc'].append(int(test_acc*1000)/1000)
        self.acc['val_acc'].append(int(val_acc*1000)/1000)       
        
class stats: 
    def __init__(self):   
        self.df1 = stats_i()
        self.df2 = stats_i()
        self.df3 = stats_i()
        self.df4 = stats_i()
        self.df = [self.df1, self.df2, self.df3, self.df4]
        
    def print(self):
        print('---------------| Statistics |-----------------')
    
        itr = 0
        for df in self.df:
            print('DataFrame %d: ' %(itr+1), df_name_list[itr])
            print('                        0.2%   0.5%   0.8%')
            print('Training Accuracy:   ', df.acc['train_acc'])
            print('Testing Accuracy:    ', df.acc['test_acc'])
            print('Validation Accuracy: ', df.acc['val_acc'])
            print()
            itr += 1

In [19]:
show_heatmaps = False

In [ ]:
import warnings
warnings.filterwarnings("ignore")

csv_stats = stats()
dec_tree_stats = stats()
knn_stats = stats()

num_percentage_trials = 3

# loop over percentages
for perc in train_list:
    
    # loop over each dataset in list
    for i in range(len(df_list)):
        test_acc_sum, val_acc_sum, train_acc_sum = 0,0,0
        for x in range(num_percentage_trials):
            test_acc, train_acc, val_acc = do_svc(df_list[i], perc)
            test_acc_sum += test_acc
            train_acc_sum += train_acc
            val_acc_sum += val_acc
        csv_stats.df[i].populate_stats(test_acc_sum/num_percentage_trials, 
                                       val_acc_sum/num_percentage_trials, 
                                       train_acc_sum/num_percentage_trials)

# loop over each dataset in list
    for i in range(len(df_list)):
        test_acc_sum, val_acc_sum, train_acc_sum = 0,0,0
        for x in range(num_percentage_trials):
            test_acc, train_acc, val_acc = do_dec_tree(df_list[i], perc)
            test_acc_sum += test_acc
            train_acc_sum += train_acc
            val_acc_sum += val_acc
        dec_tree_stats.df[i].populate_stats(test_acc_sum/num_percentage_trials, 
                                       val_acc_sum/num_percentage_trials, 
                                       train_acc_sum/num_percentage_trials)

# loop over each dataset in list
    for i in range(len(df_list)):
        test_acc_sum, val_acc_sum, train_acc_sum = 0,0,0
        for x in range(num_percentage_trials):
            test_acc, train_acc, val_acc = do_knn(df_list[i], perc)
            test_acc_sum += test_acc
            train_acc_sum += train_acc
            val_acc_sum += val_acc
        knn_stats.df[i].populate_stats(test_acc_sum/num_percentage_trials, 
                                       val_acc_sum/num_percentage_trials, 
                                       train_acc_sum/num_percentage_trials)

In [ ]:
print('---------------|    SVM     |-----------------')
csv_stats.print()

In [ ]:
print('---------------|  Dec Tree  |-----------------')
print(dec_tree_stats.print())

In [ ]:
print('---------------|    KNN     |-----------------')
print(knn_stats.print())